[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/bytefmt"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kubernetes-incubator/external-storage"
  version = "3.0.0-beta.2"

[prune]
  go-tests = true
  unused-packages = true
